name = "apartman"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[vars]
# Ove varijable se overridaju u Cloudflare dashboardu za produkciju
# Lokalno se čitaju iz .dev.vars

[[cron_triggers]]
crons = ["0 8 * * *"]
# Cron koji se pokreće svakog dana u 8:00 UTC
# Šalje podsjetnik za čišćenje dan prije check-outa
# i auto-generira račune
